package edu.uniminuto.persistencia;
// Generated 12-mar-2015 13:21:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cancion generated by hbm2java
 */
public class Cancion  implements java.io.Serializable {


     private Long id;
     private Interprete interprete;
     private String nombre;
     private String anhio;
     private Date duracion;
     private String peso;
     private String calidad;
     private int precio;
     private Set<Pedidocancion> pedidocancions = new HashSet<Pedidocancion>(0);
     private Set<Discocancion> discocancions = new HashSet<Discocancion>(0);
     private Set<Recocancion> recocancions = new HashSet<Recocancion>(0);
     private Set<Compracancion> compracancions = new HashSet<Compracancion>(0);

    public Cancion() {
    }

	
    public Cancion(Interprete interprete, String nombre, String anhio, Date duracion, String peso, String calidad, int precio) {
        this.interprete = interprete;
        this.nombre = nombre;
        this.anhio = anhio;
        this.duracion = duracion;
        this.peso = peso;
        this.calidad = calidad;
        this.precio = precio;
    }
    public Cancion(Interprete interprete, String nombre, String anhio, Date duracion, String peso, String calidad, int precio, Set<Pedidocancion> pedidocancions, Set<Discocancion> discocancions, Set<Recocancion> recocancions, Set<Compracancion> compracancions) {
       this.interprete = interprete;
       this.nombre = nombre;
       this.anhio = anhio;
       this.duracion = duracion;
       this.peso = peso;
       this.calidad = calidad;
       this.precio = precio;
       this.pedidocancions = pedidocancions;
       this.discocancions = discocancions;
       this.recocancions = recocancions;
       this.compracancions = compracancions;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Interprete getInterprete() {
        return this.interprete;
    }
    
    public void setInterprete(Interprete interprete) {
        this.interprete = interprete;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAnhio() {
        return this.anhio;
    }
    
    public void setAnhio(String anhio) {
        this.anhio = anhio;
    }
    public Date getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Date duracion) {
        this.duracion = duracion;
    }
    public String getPeso() {
        return this.peso;
    }
    
    public void setPeso(String peso) {
        this.peso = peso;
    }
    public String getCalidad() {
        return this.calidad;
    }
    
    public void setCalidad(String calidad) {
        this.calidad = calidad;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }
    public Set<Pedidocancion> getPedidocancions() {
        return this.pedidocancions;
    }
    
    public void setPedidocancions(Set<Pedidocancion> pedidocancions) {
        this.pedidocancions = pedidocancions;
    }
    public Set<Discocancion> getDiscocancions() {
        return this.discocancions;
    }
    
    public void setDiscocancions(Set<Discocancion> discocancions) {
        this.discocancions = discocancions;
    }
    public Set<Recocancion> getRecocancions() {
        return this.recocancions;
    }
    
    public void setRecocancions(Set<Recocancion> recocancions) {
        this.recocancions = recocancions;
    }
    public Set<Compracancion> getCompracancions() {
        return this.compracancions;
    }
    
    public void setCompracancions(Set<Compracancion> compracancions) {
        this.compracancions = compracancions;
    }




}


