package edu.uniminuto.persistencia;
// Generated 12-mar-2015 13:21:11 by Hibernate Tools 4.3.1



/**
 * Compradisco generated by hbm2java
 */
public class Compradisco  implements java.io.Serializable {


     private Integer id;
     private Compra compra;
     private Disco disco;
     private Persona persona;
     private long precio;
     private int calificacion;

    public Compradisco() {
    }

    public Compradisco(Compra compra, Disco disco, Persona persona, long precio, int calificacion) {
       this.compra = compra;
       this.disco = disco;
       this.persona = persona;
       this.precio = precio;
       this.calificacion = calificacion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Disco getDisco() {
        return this.disco;
    }
    
    public void setDisco(Disco disco) {
        this.disco = disco;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public long getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(long precio) {
        this.precio = precio;
    }
    public int getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(int calificacion) {
        this.calificacion = calificacion;
    }




}


