package edu.uniminuto.persistencia;
// Generated 12-mar-2015 13:21:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private Integer id;
     private Persona persona;
     private Date fecha;
     private long total;
     private String observaciones;
     private Set<Compradisco> compradiscos = new HashSet<Compradisco>(0);
     private Set<Compracancion> compracancions = new HashSet<Compracancion>(0);

    public Compra() {
    }

	
    public Compra(Persona persona, Date fecha, long total) {
        this.persona = persona;
        this.fecha = fecha;
        this.total = total;
    }
    public Compra(Persona persona, Date fecha, long total, String observaciones, Set<Compradisco> compradiscos, Set<Compracancion> compracancions) {
       this.persona = persona;
       this.fecha = fecha;
       this.total = total;
       this.observaciones = observaciones;
       this.compradiscos = compradiscos;
       this.compracancions = compracancions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public long getTotal() {
        return this.total;
    }
    
    public void setTotal(long total) {
        this.total = total;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Set<Compradisco> getCompradiscos() {
        return this.compradiscos;
    }
    
    public void setCompradiscos(Set<Compradisco> compradiscos) {
        this.compradiscos = compradiscos;
    }
    public Set<Compracancion> getCompracancions() {
        return this.compracancions;
    }
    
    public void setCompracancions(Set<Compracancion> compracancions) {
        this.compracancions = compracancions;
    }




}


