package edu.uniminuto.persistencia;
// Generated 12-mar-2015 13:21:11 by Hibernate Tools 4.3.1



/**
 * Discocancion generated by hbm2java
 */
public class Discocancion  implements java.io.Serializable {


     private Long id;
     private Cancion cancion;
     private Disco disco;

    public Discocancion() {
    }

    public Discocancion(Cancion cancion, Disco disco) {
       this.cancion = cancion;
       this.disco = disco;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Cancion getCancion() {
        return this.cancion;
    }
    
    public void setCancion(Cancion cancion) {
        this.cancion = cancion;
    }
    public Disco getDisco() {
        return this.disco;
    }
    
    public void setDisco(Disco disco) {
        this.disco = disco;
    }




}


