package edu.uniminuto.persistencia;
// Generated 12-mar-2015 13:21:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Disco generated by hbm2java
 */
public class Disco  implements java.io.Serializable {


     private Integer id;
     private Genero genero;
     private Interprete interprete;
     private String nombre;
     private String imagen;
     private Date anhio;
     private Set<Compradisco> compradiscos = new HashSet<Compradisco>(0);
     private Set<Discopropietario> discopropietarios = new HashSet<Discopropietario>(0);
     private Set<Discocancion> discocancions = new HashSet<Discocancion>(0);

    public Disco() {
    }

	
    public Disco(Genero genero, Interprete interprete, String nombre, String imagen, Date anhio) {
        this.genero = genero;
        this.interprete = interprete;
        this.nombre = nombre;
        this.imagen = imagen;
        this.anhio = anhio;
    }
    public Disco(Genero genero, Interprete interprete, String nombre, String imagen, Date anhio, Set<Compradisco> compradiscos, Set<Discopropietario> discopropietarios, Set<Discocancion> discocancions) {
       this.genero = genero;
       this.interprete = interprete;
       this.nombre = nombre;
       this.imagen = imagen;
       this.anhio = anhio;
       this.compradiscos = compradiscos;
       this.discopropietarios = discopropietarios;
       this.discocancions = discocancions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Genero getGenero() {
        return this.genero;
    }
    
    public void setGenero(Genero genero) {
        this.genero = genero;
    }
    public Interprete getInterprete() {
        return this.interprete;
    }
    
    public void setInterprete(Interprete interprete) {
        this.interprete = interprete;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public Date getAnhio() {
        return this.anhio;
    }
    
    public void setAnhio(Date anhio) {
        this.anhio = anhio;
    }
    public Set<Compradisco> getCompradiscos() {
        return this.compradiscos;
    }
    
    public void setCompradiscos(Set<Compradisco> compradiscos) {
        this.compradiscos = compradiscos;
    }
    public Set<Discopropietario> getDiscopropietarios() {
        return this.discopropietarios;
    }
    
    public void setDiscopropietarios(Set<Discopropietario> discopropietarios) {
        this.discopropietarios = discopropietarios;
    }
    public Set<Discocancion> getDiscocancions() {
        return this.discocancions;
    }
    
    public void setDiscocancions(Set<Discocancion> discocancions) {
        this.discocancions = discocancions;
    }




}


