package edu.uniminuto.persistencia;
// Generated 12-mar-2015 13:21:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Interprete generated by hbm2java
 */
public class Interprete  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<Disco> discos = new HashSet<Disco>(0);
     private Set<Cancion> cancions = new HashSet<Cancion>(0);

    public Interprete() {
    }

	
    public Interprete(String nombre) {
        this.nombre = nombre;
    }
    public Interprete(String nombre, Set<Disco> discos, Set<Cancion> cancions) {
       this.nombre = nombre;
       this.discos = discos;
       this.cancions = cancions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Disco> getDiscos() {
        return this.discos;
    }
    
    public void setDiscos(Set<Disco> discos) {
        this.discos = discos;
    }
    public Set<Cancion> getCancions() {
        return this.cancions;
    }
    
    public void setCancions(Set<Cancion> cancions) {
        this.cancions = cancions;
    }




}


