package edu.uniminuto.persistencia;
// Generated 12-mar-2015 13:21:11 by Hibernate Tools 4.3.1



/**
 * Pedidocancion generated by hbm2java
 */
public class Pedidocancion  implements java.io.Serializable {


     private Integer id;
     private Cancion cancion;
     private Pedido pedido;

    public Pedidocancion() {
    }

    public Pedidocancion(Cancion cancion, Pedido pedido) {
       this.cancion = cancion;
       this.pedido = pedido;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cancion getCancion() {
        return this.cancion;
    }
    
    public void setCancion(Cancion cancion) {
        this.cancion = cancion;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }




}


