package edu.uniminuto.persistencia;
// Generated 12-mar-2015 13:21:11 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pedidodisco generated by hbm2java
 */
public class Pedidodisco  implements java.io.Serializable {


     private Integer id;
     private Discopropietario discopropietario;
     private Pedido pedido;
     private String comentario;
     private int enviado;
     private Date fechaenvio;
     private int rechazado;

    public Pedidodisco() {
    }

	
    public Pedidodisco(Discopropietario discopropietario, Pedido pedido, int enviado, int rechazado) {
        this.discopropietario = discopropietario;
        this.pedido = pedido;
        this.enviado = enviado;
        this.rechazado = rechazado;
    }
    public Pedidodisco(Discopropietario discopropietario, Pedido pedido, String comentario, int enviado, Date fechaenvio, int rechazado) {
       this.discopropietario = discopropietario;
       this.pedido = pedido;
       this.comentario = comentario;
       this.enviado = enviado;
       this.fechaenvio = fechaenvio;
       this.rechazado = rechazado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Discopropietario getDiscopropietario() {
        return this.discopropietario;
    }
    
    public void setDiscopropietario(Discopropietario discopropietario) {
        this.discopropietario = discopropietario;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public int getEnviado() {
        return this.enviado;
    }
    
    public void setEnviado(int enviado) {
        this.enviado = enviado;
    }
    public Date getFechaenvio() {
        return this.fechaenvio;
    }
    
    public void setFechaenvio(Date fechaenvio) {
        this.fechaenvio = fechaenvio;
    }
    public int getRechazado() {
        return this.rechazado;
    }
    
    public void setRechazado(int rechazado) {
        this.rechazado = rechazado;
    }




}


