package edu.uniminuto.persistencia;
// Generated 12-mar-2015 13:21:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer id;
     private Persona persona;
     private Date fechapedido;
     private Long total;
     private Integer descartado;
     private Set<Pedidodisco> pedidodiscos = new HashSet<Pedidodisco>(0);
     private Set<Pedidocancion> pedidocancions = new HashSet<Pedidocancion>(0);

    public Pedido() {
    }

	
    public Pedido(Persona persona, Date fechapedido, int descartado) {
        this.persona = persona;
        this.fechapedido = fechapedido;
        this.descartado = descartado;
    }
    public Pedido(Persona persona, Date fechapedido, Long total, int descartado, Set<Pedidodisco> pedidodiscos, Set<Pedidocancion> pedidocancions) {
       this.persona = persona;
       this.fechapedido = fechapedido;
       this.total = total;
       this.descartado = descartado;
       this.pedidodiscos = pedidodiscos;
       this.pedidocancions = pedidocancions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Date getFechapedido() {
        return this.fechapedido;
    }
    
    public void setFechapedido(Date fechapedido) {
        this.fechapedido = fechapedido;
    }
    public Long getTotal() {
        return this.total;
    }
    
    public void setTotal(Long total) {
        this.total = total;
    }
    public Set<Pedidodisco> getPedidodiscos() {
        return this.pedidodiscos;
    }
    
    public void setPedidodiscos(Set<Pedidodisco> pedidodiscos) {
        this.pedidodiscos = pedidodiscos;
    }
    public Set<Pedidocancion> getPedidocancions() {
        return this.pedidocancions;
    }
    
    public void setPedidocancions(Set<Pedidocancion> pedidocancions) {
        this.pedidocancions = pedidocancions;
    }

    /**
     * @return the descartado
     */
    public Integer getDescartado() {
        return descartado;
    }

    /**
     * @param descartado the descartado to set
     */
    public void setDescartado(Integer descartado) {
        this.descartado = descartado;
    }




}


